### ISSUE TITLE
ubuntu 18.04

### ISSUE THREAD

**Issue by baharalidurrani** [Munawwar/ubuntu-gestures#2]
ubuntu 18.04 have Gnome instead of Unity desktop...

**Comment by Munawwar** [comment]
Ah. I don't know yet what can be done. I am still using 16.04

**Comment by baharalidurrani** [comment]
I have found a great tool for that.
[https://github.com/baharalidurrani/libinput-gestures](url)

**Comment by baharalidurrani** [comment]
I have found a great tool for that.
[https://github.com/baharalidurrani/libinput-gestures](https://github.com/baharalidurrani/libinput-gestures)
